export default {
    WINDOW_RESIZE: 'WINDOW_RESIZE',
    ROUTE_CHANGED: 'ROUTE_CHANGED',
    PAGE_ASSETS_LOADED: 'PAGE_ASSETS_LOADED',
    INITIAL_PAGE_ASSETS_LOADED: 'INITIAL_PAGE_ASSETS_LOADED',
    LOAD_NEXT_PREVIOUS_PAGE_ASSETS: 'LOAD_NEXT_PREVIOUS_PAGE_ASSETS',
    APP_START: 'APP_START',
    SHOW_TITLE: 'SHOW_TITLE',
    HIDE_TITLE: 'HIDE_TITLE',
    TITLE_CANVAS_ENTER: 'TITLE_CANVAS_ENTER',
    TITLE_CANVAS_LEAVE: 'TITLE_CANVAS_LEAVE',
    UPDATE_CARDS: 'UPDATE_CARDS',
    MAIN_ARROW_OVER: 'MAIN_ARROW_OVER',
    MAIN_ARROW_OUT: 'MAIN_ARROW_OUT',

    OPEN_INDEX: 'OPEN_INDEX',
    CLOSE_INDEX: 'CLOSE_INDEX',

    INDEX_EASE: Elastic.easeOut,
    INDEX_TIME: 1.6,
    INDEX_TIMEOUT: 250,

    START_MORPHING: 'START_MORPHING',
    LOAD_MORPHING: 'LOAD_MORPHING',
    DID_LOAD_MORPHING: 'DID_LOAD_MORPHING',
    DID_FINISH_MORPHING: 'DID_FINISH_MORPHING',

    SHOW_INTERFACE: 'SHOW_INTERFACE',
    HIDE_INTERFACE: 'HIDE_INTERFACE',

    SHOW_PERSON_INFO: 'SHOW_PERSON_INFO',
    SHOW_PERSON_VIDEO: 'SHOW_PERSON_VIDEO',

    ORIENTATION: {
        LANDSCAPE: 'LANDSCAPE',
        PORTRAIT: 'PORTRAIT'
    },

    GROUP: {
        KINGS: 'kings',
        ARMOURS: 'armours',
        DINO: 'dino',
        SPORT: 'sport'
    },

    NEXT_PERSON: 'NEXT_PERSON',
    PREVIOUS_PERSON: 'PREVIOUS_PERSON',

    PORTRAIT: 'PORTRAIT',
    PRODUCT: 'PRODUCT',

    FORWARD: 'FORWARD',
    BACKWARD: 'BACKWARD',

    LEFT: 'LEFT',
    RIGHT: 'RIGHT',
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',

    PORTRAIT_TRANSITION: {
        WILL_START: 'WILL_START',
        DID_REACH_HALF_TIME: 'DID_REACH_HALF_TIME'
    },

    PX_CONTAINER_IS_READY: 'PX_CONTAINER_IS_READY',
    PX_CONTAINER_ADD_CHILD: 'PX_CONTAINER_ADD_CHILD',
    PX_CONTAINER_REMOVE_CHILD: 'PX_CONTAINER_REMOVE_CHILD',

    PADDING_AROUND: 40,

    MEDIA_GLOBAL_W: 1920,
    MEDIA_GLOBAL_H: 1080,

    MEDIA_MOBILE_W: 570,
    MEDIA_MOBILE_H: 750,

    TITLE_W: 800,
    TITLE_H: 450,

    TRANSITION_SPRITE_W: 700,
    TRANSITION_SPRITE_H: 394,

    MIN_MIDDLE_W: 960,
    MQ_XSMALL: 320,
    MQ_SMALL: 480,
    MQ_MEDIUM: 768,
    MQ_LARGE: 1024,
    MQ_XLARGE: 1280,
    MQ_XXLARGE: 1680
}
